pub struct Config {
    phrases: Vec<String>,
}
pub const PHRASES: [&str; 20] = [
    "The quick brown fox jumps over the lazy dog.",
    "Pack my box with five dozen liquor jugs.",
    "How quickly daft jumping zebras vex.",
    "Sphinx of black quartz, judge my vow.",
    "Jackdaws love my big sphinx of quartz.",
    "Mr. Jock, TV quiz PhD, bags few lynx.",
    "Waltz, nymph, for quick jigs vex Bud.",
    "Crazy Frederick bought many very exquisite opal jewels.",
    "Sixty zippers were quickly picked from the woven jute bag.",
    "Grumpy wizards make toxic brew for the evil Queen and Jack.",
    "Bored? Craving a pub quiz fix? Why, just come to the Royal Oak!",
    "The five boxing wizards jump quickly.",
    "Fickle jinx bog dwarves spy math quiz.",
    "Cwm fjord bank glyphs vext quiz.",
    "Blowzy night-frumps vex'd Jack Q.",
    "Squdgy fez, blank jimp crwth vox!",
    "Huzzah! Mr. Sphinx enjoys liquor of the gods.",
    "Jumping jacks vex big quick fox nymph.",
    "Big July earthquakes confound zany experimental vow.",
    "Few quips galvanized the mock jury box.",
];
